language: python
python:
  - "2.7"
install:
  - sudo apt-get install python-pyside
  - pip install -r tests/requirements.txt --use-mirrors
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ln -s /usr/lib/python2.7/dist-packages/PySide /home/vagrant/virtualenv/python2.7/lib/python2.7/site-packages/PySide -v
script: tests/run.py -v
